### ISSUE TITLE
问题和优化建议

### ISSUE THREAD

**Issue by Chinakentgao** [VMsec/ihoneyBakFileScan_Modify#2]
问题1:经常出现输入ip地址后读取比如python ihoneyBakFileScan_Modify.py -u http://1.2.3.4:9999/
然后就一直卡在[add check] http://1.2.3.4:9999/2.tar.tgz 这个地方没反应 试过好几次都是这样
[add check] http://1.2.3.4:9999/1234.bak
[add check] http://1.2.3.4:9999/234.bak
[add check] http://1.2.3.4:9999/2.3.4.bak
[add check] http://1.2.3.4:9999/1.bak
[add check] http://1.2.3.4:9999/2.bak
[add check] http://1.2.3.4:9999/1.2.3.4.sql
[add check] http://1.2.3.4:9999/1234.sql
[add check] http://1.2.3.4:9999/234.sql
[add check] http://1.2.3.4:9999/2.3.4.sql
[add check] http://1.2.3.4:9999/1.sql
[add check] http://1.2.3.4:9999/2.sql
[add check] http://1.2.3.4:9999/1.2.3.4.gz
[add check] http://1.2.3.4:9999/1234.gz
[add check] http://1.2.3.4:9999/234.gz
[add check] http://1.2.3.4:9999/2.3.4.gz
[add check] http://1.2.3.4:9999/1.gz
[add check] http://1.2.3.4:9999/2.gz
[add check] http://1.2.3.4:9999/1.2.3.4.sql.gz
[add check] http://1.2.3.4:9999/1234.sql.gz
[add check] http://1.2.3.4:9999/234.sql.gz
[add check] http://1.2.3.4:9999/2.3.4.sql.gz
[add check] http://1.2.3.4:9999/1.sql.gz
[add check] http://1.2.3.4:9999/2.sql.gz
[add check] http://1.2.3.4:9999/1.2.3.4.tar.tgz
[add check] http://1.2.3.4:9999/1234.tar.tgz
[add check] http://1.2.3.4:9999/234.tar.tgz
[add check] http://1.2.3.4:9999/2.3.4.tar.tgz
[add check] http://1.2.3.4:9999/1.tar.tgz
[add check] http://1.2.3.4:9999/2.tar.tgz  每次跑都到这里卡主没任何反应 也不是网络问题测试能访问就是不能读取完开始扫描
问题2：好像是索引问题就是当批量扫描的目标太多的时候就会出现超出索引的情况。具体多少我忘记了
优化建议：扫描的过程中如果访问目标出现超时的情况自动切换下个ip，或者单个IP直接结束扫描。现在的情况经常就扫一半卡那边没反应了 也没办法结束必须得强制结束

**Comment by r00tSe7en** [comment]
方便发目标来测试吗，你说的问题我没有遇到，测试脚本是正常的，可以加个代理端口挂到burp看下请求包什么情况。
然后脚本里是有请求超时设置的，有时候网络波动情况下导致的暂时超时无法避免，所以超时自动切换ip的话可以自行 在vlun函数中添加代码实现
索引的问题，32位的平台（Python）下List最多能有2**31-1个元素，64位的平台（Python）下List最多能有2**63-1个元素，基本超不了这个数。

**Comment by r00tSe7en** [comment]
多线程跑到最后是会死锁，我看看解决下

**Comment by r00tSe7en** [comment]
> 问题1:经常出现输入ip地址后读取比如python ihoneyBakFileScan_Modify.py -u http://1.2.3.4:9999/ 然后就一直卡在[add check] http://1.2.3.4:9999/2.tar.tgz 这个地方没反应 试过好几次都是这样 [add check] http://1.2.3.4:9999/1234.bak [add check] http://1.2.3.4:9999/234.bak [add check] http://1.2.3.4:9999/2.3.4.bak [add check] http://1.2.3.4:9999/1.bak [add check] http://1.2.3.4:9999/2.bak [add check] http://1.2.3.4:9999/1.2.3.4.sql [add check] http://1.2.3.4:9999/1234.sql [add check] http://1.2.3.4:9999/234.sql [add check] http://1.2.3.4:9999/2.3.4.sql [add check] http://1.2.3.4:9999/1.sql [add check] http://1.2.3.4:9999/2.sql [add check] http://1.2.3.4:9999/1.2.3.4.gz [add check] http://1.2.3.4:9999/1234.gz [add check] http://1.2.3.4:9999/234.gz [add check] http://1.2.3.4:9999/2.3.4.gz [add check] http://1.2.3.4:9999/1.gz [add check] http://1.2.3.4:9999/2.gz [add check] http://1.2.3.4:9999/1.2.3.4.sql.gz [add check] http://1.2.3.4:9999/1234.sql.gz [add check] http://1.2.3.4:9999/234.sql.gz [add check] http://1.2.3.4:9999/2.3.4.sql.gz [add check] http://1.2.3.4:9999/1.sql.gz [add check] http://1.2.3.4:9999/2.sql.gz [add check] http://1.2.3.4:9999/1.2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1234.tar.tgz [add check] http://1.2.3.4:9999/234.tar.tgz [add check] http://1.2.3.4:9999/2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1.tar.tgz [add check] http://1.2.3.4:9999/2.tar.tgz 每次跑都到这里卡主没任何反应 也不是网络问题测试能访问就是不能读取完开始扫描 问题2：好像是索引问题就是当批量扫描的目标太多的时候就会出现超出索引的情况。具体多少我忘记了 优化建议：扫描的过程中如果访问目标出现超时的情况自动切换下个ip，或者单个IP直接结束扫描。现在的情况经常就扫一半卡那边没反应了 也没办法结束必须得强制结束

参考readme更新的内容，应该没有问题了，方便的话可以再测试下是否正常

**Comment by Chinakentgao** [comment]
更新完直接原来的命令都没办法执行报错了
python ihoneyBakFileScan_Modify.py -t 30 -u http://xxxx/
[!] Please specify a URL, or URL file name, or RESULT file name.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月22日(星期三) 下午4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VMsec/ihoneyBakFileScan_Modify] 问题和优化建议 (Issue #2)





  
问题1:经常出现输入ip地址后读取比如python ihoneyBakFileScan_Modify.py -u http://1.2.3.4:9999/ 然后就一直卡在[add check] http://1.2.3.4:9999/2.tar.tgz 这个地方没反应 试过好几次都是这样 [add check] http://1.2.3.4:9999/1234.bak [add check] http://1.2.3.4:9999/234.bak [add check] http://1.2.3.4:9999/2.3.4.bak [add check] http://1.2.3.4:9999/1.bak [add check] http://1.2.3.4:9999/2.bak [add check] http://1.2.3.4:9999/1.2.3.4.sql [add check] http://1.2.3.4:9999/1234.sql [add check] http://1.2.3.4:9999/234.sql [add check] http://1.2.3.4:9999/2.3.4.sql [add check] http://1.2.3.4:9999/1.sql [add check] http://1.2.3.4:9999/2.sql [add check] http://1.2.3.4:9999/1.2.3.4.gz [add check] http://1.2.3.4:9999/1234.gz [add check] http://1.2.3.4:9999/234.gz [add check] http://1.2.3.4:9999/2.3.4.gz [add check] http://1.2.3.4:9999/1.gz [add check] http://1.2.3.4:9999/2.gz [add check] http://1.2.3.4:9999/1.2.3.4.sql.gz [add check] http://1.2.3.4:9999/1234.sql.gz [add check] http://1.2.3.4:9999/234.sql.gz [add check] http://1.2.3.4:9999/2.3.4.sql.gz [add check] http://1.2.3.4:9999/1.sql.gz [add check] http://1.2.3.4:9999/2.sql.gz [add check] http://1.2.3.4:9999/1.2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1234.tar.tgz [add check] http://1.2.3.4:9999/234.tar.tgz [add check] http://1.2.3.4:9999/2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1.tar.tgz [add check] http://1.2.3.4:9999/2.tar.tgz 每次跑都到这里卡主没任何反应 也不是网络问题测试能访问就是不能读取完开始扫描 问题2：好像是索引问题就是当批量扫描的目标太多的时候就会出现超出索引的情况。具体多少我忘记了 优化建议：扫描的过程中如果访问目标出现超时的情况自动切换下个ip，或者单个IP直接结束扫描。现在的情况经常就扫一半卡那边没反应了 也没办法结束必须得强制结束
  
参考readme更新的内容，应该没有问题了，方便的话可以再测试下是否正常

**Comment by r00tSe7en** [comment]
> 更新完直接原来的命令都没办法执行报错了 python ihoneyBakFileScan_Modify.py -t 30 -u http://xxxx/ [!] Please specify a URL, or URL file name, or RESULT file name.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月22日(星期三) 下午4:53 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [VMsec/ihoneyBakFileScan_Modify] 问题和优化建议 (Issue #2) 问题1:经常出现输入ip地址后读取比如python ihoneyBakFileScan_Modify.py -u http://1.2.3.4:9999/ 然后就一直卡在[add check] http://1.2.3.4:9999/2.tar.tgz 这个地方没反应 试过好几次都是这样 [add check] http://1.2.3.4:9999/1234.bak [add check] http://1.2.3.4:9999/234.bak [add check] http://1.2.3.4:9999/2.3.4.bak [add check] http://1.2.3.4:9999/1.bak [add check] http://1.2.3.4:9999/2.bak [add check] http://1.2.3.4:9999/1.2.3.4.sql [add check] http://1.2.3.4:9999/1234.sql [add check] http://1.2.3.4:9999/234.sql [add check] http://1.2.3.4:9999/2.3.4.sql [add check] http://1.2.3.4:9999/1.sql [add check] http://1.2.3.4:9999/2.sql [add check] http://1.2.3.4:9999/1.2.3.4.gz [add check] http://1.2.3.4:9999/1234.gz [add check] http://1.2.3.4:9999/234.gz [add check] http://1.2.3.4:9999/2.3.4.gz [add check] http://1.2.3.4:9999/1.gz [add check] http://1.2.3.4:9999/2.gz [add check] http://1.2.3.4:9999/1.2.3.4.sql.gz [add check] http://1.2.3.4:9999/1234.sql.gz [add check] http://1.2.3.4:9999/234.sql.gz [add check] http://1.2.3.4:9999/2.3.4.sql.gz [add check] http://1.2.3.4:9999/1.sql.gz [add check] http://1.2.3.4:9999/2.sql.gz [add check] http://1.2.3.4:9999/1.2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1234.tar.tgz [add check] http://1.2.3.4:9999/234.tar.tgz [add check] http://1.2.3.4:9999/2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1.tar.tgz [add check] http://1.2.3.4:9999/2.tar.tgz 每次跑都到这里卡主没任何反应 也不是网络问题测试能访问就是不能读取完开始扫描 问题2：好像是索引问题就是当批量扫描的目标太多的时候就会出现超出索引的情况。具体多少我忘记了 优化建议：扫描的过程中如果访问目标出现超时的情况自动切换下个ip，或者单个IP直接结束扫描。现在的情况经常就扫一半卡那边没反应了 也没办法结束必须得强制结束 参考readme更新的内容，应该没有问题了，方便的话可以再测试下是否正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

新加了一个参数 -o，使用这个 python ihoneyBakFileScan_Modify.py -t 30 -u http://xxxx/ -o result.txt

**Comment by Chinakentgao** [comment]
> > 更新完直接原来的命令都没办法执行报错了 python ihoneyBakFileScan_Modify.py -t 30 -u http://xxxx/ [!] Please specify a URL, or URL file name, or RESULT file name.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年6月22日(星期三) 下午4:53 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [VMsec/ihoneyBakFileScan_Modify] 问题和优化建议 (Issue #2) 问题1:经常出现输入ip地址后读取比如python ihoneyBakFileScan_Modify.py -u http://1.2.3.4:9999/ 然后就一直卡在[add check] http://1.2.3.4:9999/2.tar.tgz 这个地方没反应 试过好几次都是这样 [add check] http://1.2.3.4:9999/1234.bak [add check] http://1.2.3.4:9999/234.bak [add check] http://1.2.3.4:9999/2.3.4.bak [add check] http://1.2.3.4:9999/1.bak [add check] http://1.2.3.4:9999/2.bak [add check] http://1.2.3.4:9999/1.2.3.4.sql [add check] http://1.2.3.4:9999/1234.sql [add check] http://1.2.3.4:9999/234.sql [add check] http://1.2.3.4:9999/2.3.4.sql [add check] http://1.2.3.4:9999/1.sql [add check] http://1.2.3.4:9999/2.sql [add check] http://1.2.3.4:9999/1.2.3.4.gz [add check] http://1.2.3.4:9999/1234.gz [add check] http://1.2.3.4:9999/234.gz [add check] http://1.2.3.4:9999/2.3.4.gz [add check] http://1.2.3.4:9999/1.gz [add check] http://1.2.3.4:9999/2.gz [add check] http://1.2.3.4:9999/1.2.3.4.sql.gz [add check] http://1.2.3.4:9999/1234.sql.gz [add check] http://1.2.3.4:9999/234.sql.gz [add check] http://1.2.3.4:9999/2.3.4.sql.gz [add check] http://1.2.3.4:9999/1.sql.gz [add check] http://1.2.3.4:9999/2.sql.gz [add check] http://1.2.3.4:9999/1.2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1234.tar.tgz [add check] http://1.2.3.4:9999/234.tar.tgz [add check] http://1.2.3.4:9999/2.3.4.tar.tgz [add check] http://1.2.3.4:9999/1.tar.tgz [add check] http://1.2.3.4:9999/2.tar.tgz 每次跑都到这里卡主没任何反应 也不是网络问题测试能访问就是不能读取完开始扫描 问题2：好像是索引问题就是当批量扫描的目标太多的时候就会出现超出索引的情况。具体多少我忘记了 优化建议：扫描的过程中如果访问目标出现超时的情况自动切换下个ip，或者单个IP直接结束扫描。现在的情况经常就扫一半卡那边没反应了 也没办法结束必须得强制结束 参考readme更新的内容，应该没有问题了，方便的话可以再测试下是否正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 新加了一个参数 -o，使用这个 python ihoneyBakFileScan_Modify.py -t 30 -u http://xxxx/ -o result.txt
你应该把 -o result.txt设置成非必须参数 突然多个有点不习惯
